pipeline {
    agent any
    environment {
        BRANCH_NAME_WITHOUT_UNDERSCORES = "${env.BRANCH_NAME}".replaceAll("_", "")
        MANIFEST = getManifest(BRANCH_NAME_WITHOUT_UNDERSCORES)
    }
    tools {
        jdk 'openjdk-11-jdk'
        nodejs 'node'
    }
    stages {
        stage('Npm Install') {
            steps {
                dir("ui") {
                    sh "npm install"
                }
            }
        }

        stage('Run Tests') {
            parallel {
                stage('API Test') {
                    steps {
                        dir("api") {
                            sh "./gradlew clean test"
                        }
                    }
                }

                stage('UI Test') {
                    steps {
                        dir("ui") {
                            sh "CI=true npm run test:ci"
                        }
                    }
                }

            }
        }

        stage('Build') {
            parallel {
                stage('API Build') {
                    steps {
                        dir("api") {
                            sh "./gradlew assemble"
                        }
                    }
                }
                stage('UI Build') {
                    steps {
                        dir("ui") {
                            sh "npm run build"
                        }
                    }
                }
            }
        }

        stage("Deploy") {
            parallel {
                stage('API Deploy Stage') {
                    when {
                        branch 'stage'
                    }
                    steps {
                        withCredentials([
                            usernamePassword(credentialsId: 'flipJenkins', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD'),
                            usernamePassword(credentialsId: 'peopleMoverDB', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASSWORD')
                        ]) {
                            dir("api") {
                                sh 'echo Pushing to Cloud Foundry'
                                sh """./gradlew cf-push-blue-green \
                                        -PbranchNameWithoutUnderscores=Stage \
                                        -Pcf.name=StagePeopleMoverAPI \
                                        -Pcf.host=stagepeoplemoverui \
                                        -Pcf.ccHost=$peoplemover_pcf_cchost \
                                        -Pcf.domain=$peoplemover_pcf_domain \
                                        -Pcf.ccUser=$JENKINS_USER \
                                        -Pcf.ccPassword=$JENKINS_PASSWORD \
                                        -Pcf.environment.spring.security.oauth2.resourceserver.jwt.issuer-uri=$spring_security_oauth2_resourceserver_jwt_issuer_uri \
                                        -Pcf.environment.adfs-resource-uri=$adfs_resource_uri \
                                        -Pcf.environment.react.app.auth_enabled=true \
                                        -Pcf.environment.react.app.invite_users_to_space_enabled=true \
                                        -Pcf.environment.react.app.adfs_url_template="$adfs_url_template" \
                                        -Pcf.environment.react.app.adfs_client_id=$adfs_client_id \
                                        -Pcf.environment.react.app.adfs_resource=$adfs_resource \
                                """.stripIndent()
                            }
                        }
                    }
                }
                stage('API Deploy Prod') {
                    when {
                        branch 'master'
                    }
                    steps {
                        withCredentials([
                            usernamePassword(credentialsId: 'flipJenkins', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD'),
                            usernamePassword(credentialsId: 'peopleMoverDB', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASSWORD')
                        ]) {
                            dir("api") {
                                sh 'echo Pushing to Cloud Foundry'
                                sh """./gradlew cf-push-blue-green \
                                        -PbranchNameWithoutUnderscores=Prod \
                                        -Pcf.name=PeopleMover2API \
                                        -Pcf.host=peoplemoverui2 \
                                        -Pcf.ccUser=$JENKINS_USER \
                                        -Pcf.ccPassword=$JENKINS_PASSWORD \
                                        -Pcf.ccHost=$peoplemover_pcf_cchost \
                                        -Pcf.domain=$peoplemover_pcf_domain \
                                        -Pcf.environment.spring.security.oauth2.resourceserver.jwt.issuer-uri=$spring_security_oauth2_resourceserver_jwt_issuer_uri \
                                        -Pcf.environment.adfs-resource-uri=$adfs_resource_uri \
                                        -Pcf.environment.react.app.auth_enabled=true \
                                        -Pcf.environment.react.app.invite_users_to_space_enabled=true \
                                        -Pcf.environment.react.app.adfs_url_template="$adfs_url_template" \
                                        -Pcf.environment.react.app.adfs_client_id=$adfs_client_id \
                                        -Pcf.environment.react.app.adfs_resource=$adfs_resource \
                                """.stripIndent()
                            }
                        }
                    }
                }
                stage('API Deploy Branch') {
                    when {
                        not {
                            anyOf {
                                branch 'master';
                                branch 'stage'
                            }
                        }
                    }
                    steps {
                        withCredentials([
                                usernamePassword(credentialsId: 'flipJenkins', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD'),
                                usernamePassword(credentialsId: 'peopleMoverDB', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASSWORD')
                        ]) {
                            dir("api") {
                                sh 'echo Pushing to Cloud Foundry'
                                sh """./gradlew cf-push-blue-green \
                                        -PbranchNameWithoutUnderscores=Branch \
                                        -Pcf.name=${env.BRANCH_NAME_WITHOUT_UNDERSCORES}API \
                                        -Pcf.host=${env.BRANCH_NAME_WITHOUT_UNDERSCORES}ui \
                                        -Pcf.ccHost=$peoplemover_pcf_cchost \
                                        -Pcf.domain=$peoplemover_pcf_domain \
                                        -Pcf.ccUser=$JENKINS_USER \
                                        -Pcf.ccPassword=$JENKINS_PASSWORD \
                                        -Pcf.environment.spring.security.oauth2.resourceserver.jwt.issuer-uri=$spring_security_oauth2_resourceserver_jwt_issuer_uri \
                                        -Pcf.environment.adfs-resource-uri=$adfs_resource_uri \
                                        -Pcf.environment.react.app.auth_enabled=false \
                                        -Pcf.environment.react.app.invite_users_to_space_enabled=true \
                                        -Pcf.environment.react.app.adfs_url_template="$adfs_url_template" \
                                        -Pcf.environment.react.app.adfs_client_id=$adfs_client_id \
                                        -Pcf.environment.react.app.adfs_resource=$adfs_resource \
                                """.stripIndent()
                            }
                        }
                    }
                }


                stage('UI Deploy') {
                    steps {
                        dir("ui") {
                            pushToCloudFoundry(
                                target: "$peoplemover_pcf_cchost",
                                organization: 'FordLabs_Experiments_InternalProjects_EDC1_Prod',
                                cloudSpace: 'FordLabs_Experiments_InternalProjects-prod',
                                credentialsId: 'flipJenkins',
                                manifestChoice: [
                                    manifestFile: "${env.MANIFEST}",
                                ]
                            )
                        }
                    }
                }
            }
        }
    }
}

def getManifest(branchName) {
    if (branchName == "dev") {
        return 'manifest_QA.yml'
    } else if (branchName == "stage") {
        return 'manifest_Stage.yml'
    } else if (branchName == "master"){
        return 'manifest.yml'
    } else {
        def filename = 'ui/manifest_QA.yml'
        def data = readYaml file: filename
        data.applications.get(0).name = "${branchName}UI"

        sh "rm $filename"
        writeYaml file: filename, data: data
        return 'manifest_QA.yml'
    }
}
