name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch here's a comment
  push:
    branches:
      - test-custom-versioning

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 13.x
      - name: Print version
        run: cat package.json
        working-directory: ./ui
      - name: Increment version
        run: npm version patch
        working-directory: ./ui
      - name: Print version
        run: cat package.json
        working-directory: ./ui
      - name: Copy version to meta.json
        run: npm run generate-build-version
        working-directory: ./ui
      - name: Push to branch
        run: git push origin test-custom-versioning
        working-directory: ./ui
