name: build

on:
  push:
    branches: [ stage, master ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11.x'
    
    - name: Test with Gradle
      run: ./gradlew clean test
      working-directory: ./api

    - name: Build with Gradle
      run: ./gradlew assemble
      working-directory: ./api

    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    
    - name: Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: PeopleMover-0.0.1-SNAPSHOT.${{ env.BRANCH_NAME }}.jar
        path: api/build/libs/PeopleMover-0.0.1-SNAPSHOT.jar
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 13.x
      - name: NPM Install
        run: npm install
        working-directory: ./ui
      - name: Test
        run: npm run test:ci
        working-directory: ./ui
      - name: Build
        run: npm run build
        working-directory: ./ui
