name: build

on:
  push:
    branches: [ stage, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11.x'
    
    - name: Test with Gradle
      run: ./gradlew clean test
      working-directory: ./api

    - name: Build with Gradle
      run: ./gradlew assemble
      working-directory: ./api

    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    
    - name: Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: PeopleMover-0.0.1-SNAPSHOT.${{ env.BRANCH_NAME }}.jar
        path: api/build/libs/PeopleMover-0.0.1-SNAPSHOT.jar
