name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11.x'
    
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3
    
    - name: Test with Gradle
      run: ./gradlew clean test

    - name: Build with Gradle
      run: ./gradlew assemble
