name: build-frontend
on:
  push:
    branches: [ stage, master ]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 13.x
      - name: Install
        run: npm install
        working-directory: ./ui
      - name: Test with NPM
        run: npm run test
        working-directory: ./ui
        env:
          CI: true
