name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    pull_request:
    branches:
      - stage

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11.x'
    - name: Test
      run: ./gradlew clean test
      working-directory: ./api
    - name: Build
      run: ./gradlew assemble
      working-directory: ./api
    - name: Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: peoplemover-api.jar
        path: api/build/libs/PeopleMover-0.0.1-SNAPSHOT.jar
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 13.x
      - name: NPM Install
        run: npm install
        working-directory: ./ui
      - name: Lint
        run: npm run lint
        working-directory: ./ui
      - name: Unit Tests
        run: npm run test:unit:ci
        working-directory: ./ui
      - name: Build
        run: npm run build
        working-directory: ./ui
      - name: Zip Build
        run: zip -r peoplemover-ui.zip build
        working-directory: ./ui
      - name: Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: peoplemover-ui.zip
          path: ui/peoplemover-ui.zip
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 13.x
      - name: NPM Install
        run: npm install
        working-directory: ./ui
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.x'
      - name: Test
        run: npm run test:e2e:ci
        working-directory: ./ui
      - name: Upload Screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: /home/runner/work/PeopleMover/PeopleMover/ui/cypress/
