name: sonarqube

on:
  pull_request:
    branches: [ stage, master ]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11.x'

    - name: Test API with Sonarqube
      run: ./gradlew sonarqube
      working-directory: ./api

    - name: Setup Node
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 13.x

    - name: NPM Install
      run: npm install
      working-directory: ./ui

    - name: Test UI with Sonarqube Coverage
      run: npm run coverage
      working-directory: ./ui

    - name: Test UI with Sonarqube Analyze
      run: npm run analyze
      working-directory: ./ui
